# Generated by Django 4.2.3 on 2023-07-08 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0016_alter_branch_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open_critical", models.IntegerField(default=0)),
                ("open_high", models.IntegerField(default=0)),
                ("open_medium", models.IntegerField(default=0)),
                ("open_low", models.IntegerField(default=0)),
                ("open_none", models.IntegerField(default=0)),
                ("open_unknown", models.IntegerField(default=0)),
                ("open", models.IntegerField(default=0)),
                ("resolved", models.IntegerField(default=0)),
                ("duplicate", models.IntegerField(default=0)),
                ("false_positive", models.IntegerField(default=0)),
                ("in_review", models.IntegerField(default=0)),
                ("not_affected", models.IntegerField(default=0)),
                ("not_security", models.IntegerField(default=0)),
                ("risk_accepted", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.product"),
                ),
            ],
            options={
                "unique_together": {("product", "date")},
            },
        ),
    ]
