# Generated by Django 4.2.3 on 2023-07-10 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Metrics_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
