# Generated by Django 4.2.3 on 2023-07-14 18:44

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EPSS_Scores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve", models.CharField(max_length=20, unique=True)),
                (
                    "epss_score",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "epss_percentile",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EPSS_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_date", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
