# Generated by Django 4.2.3 on 2023-07-15 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epss", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EPSS_Scores",
            new_name="EPSS_Score",
        ),
    ]
