# Generated by Django 5.1.6 on 2025-03-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epss", "0002_rename_epss_scores_epss_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enriched_CVSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve", models.CharField(max_length=255, unique=True)),
                ("base_cvss_vector", models.CharField(blank=True, max_length=255)),
                ("cisa_kev", models.BooleanField(default=False)),
                ("vulncheck_kev", models.BooleanField(default=False)),
                ("exploitdb", models.BooleanField(default=False)),
                ("metasploit", models.BooleanField(default=False)),
                ("nuclei", models.BooleanField(default=False)),
                ("poc_github", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="epss_score",
            name="cve",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
