# Generated by Django 5.1.5 on 2025-01-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OSV_Cache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osv_id", models.CharField(max_length=255, unique=True)),
                ("data", models.TextField()),
                ("modified", models.DateTimeField()),
            ],
        ),
    ]
