class CSAF_Tracking_Status:
    CSAF_TRACKING_STATUS_DRAFT = "draft"
    CSAF_TRACKING_STATUS_FINAL = "final"
    CSAF_TRACKING_STATUS_INTERIM = "interim"

    CSAF_TRACKING_STATUS_CHOICES = [
        (CSAF_TRACKING_STATUS_DRAFT, CSAF_TRACKING_STATUS_DRAFT),
        (CSAF_TRACKING_STATUS_FINAL, CSAF_TRACKING_STATUS_FINAL),
        (CSAF_TRACKING_STATUS_INTERIM, CSAF_TRACKING_STATUS_INTERIM),
    ]


class CSAF_Publisher_Category:
    CSAF_PUBLISHER_CATEGORY_COORDINATOR = "coordinator"
    CSAF_PUBLISHER_CATEGORY_DISCOVERER = "discoverer"
    CSAF_PUBLISHER_CATEGORY_OTHER = "other"
    CSAF_PUBLISHER_CATEGORY_TRANSLATOR = "translator"
    CSAF_PUBLISHER_CATEGORY_USER = "user"
    CSAF_PUBLISHER_CATEGORY_VENDOR = "vendor"

    CSAF_PUBLISHER_CATEGORY_CHOICES = [
        (CSAF_PUBLISHER_CATEGORY_COORDINATOR, CSAF_PUBLISHER_CATEGORY_COORDINATOR),
        (CSAF_PUBLISHER_CATEGORY_DISCOVERER, CSAF_PUBLISHER_CATEGORY_DISCOVERER),
        (CSAF_PUBLISHER_CATEGORY_OTHER, CSAF_PUBLISHER_CATEGORY_OTHER),
        (CSAF_PUBLISHER_CATEGORY_TRANSLATOR, CSAF_PUBLISHER_CATEGORY_TRANSLATOR),
        (CSAF_PUBLISHER_CATEGORY_USER, CSAF_PUBLISHER_CATEGORY_USER),
        (CSAF_PUBLISHER_CATEGORY_VENDOR, CSAF_PUBLISHER_CATEGORY_VENDOR),
    ]


class OpenVEX_Status:
    OPEN_VEX_STATUS_NOT_AFFECTED = "not_affected"
    OPEN_VEX_STATUS_AFFECTED = "affected"
    OPEN_VEX_STATUS_FIXED = "fixed"
    OPEN_VEX_STATUS_UNDER_INVESTIGATION = "under_investigation"
