class CSAF_Status:
    CSAF_STATUS_DRAFT = "draft"
    CSAF_STATUS_FINAL = "final"
    CSAF_STATUS_INTERIM = "interim"

    CSAF_STATUS_CHOICES = [
        (CSAF_STATUS_DRAFT, CSAF_STATUS_DRAFT),
        (CSAF_STATUS_FINAL, CSAF_STATUS_FINAL),
        (CSAF_STATUS_INTERIM, CSAF_STATUS_INTERIM),
    ]


class CSAF_Role:
    CSAF_ROLE_COORDINATOR = "coordinator"
    CSAF_ROLE_DISCOVERER = "discoverer"
    CSAF_ROLE_OTHER = "other"
    CSAF_ROLE_TRANSLATOR = "translator"
    CSAF_ROLE_USER = "user"
    CSAF_ROLE_VENDOR = "vendor"

    CSAF_ROLE_CHOICES = [
        (CSAF_ROLE_COORDINATOR, CSAF_ROLE_COORDINATOR),
        (CSAF_ROLE_DISCOVERER, CSAF_ROLE_DISCOVERER),
        (CSAF_ROLE_OTHER, CSAF_ROLE_OTHER),
        (CSAF_ROLE_TRANSLATOR, CSAF_ROLE_TRANSLATOR),
        (CSAF_ROLE_USER, CSAF_ROLE_USER),
        (CSAF_ROLE_VENDOR, CSAF_ROLE_VENDOR),
    ]


class OpenVEX_Status:
    OPEN_VEX_STATUS_NOT_AFFECTED = "not_affected"
    OPEN_VEX_STATUS_AFFECTED = "affected"
    OPEN_VEX_STATUS_FIXED = "fixed"
    OPEN_VEX_STATUS_UNDER_INVESTIGATION = "under_investigation"
