version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: secobserve_frontend
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://localhost:8000
      AAD_ENABLE: true
      AAD_AUTHORITY: dummy
      AAD_CLIENT_ID: dummy
      AAD_REDIRECT_URI: dummy
      AAD_POST_LOGOUT_REDIRECT_URI: dummy
      AAD_SCOPE: dummy

  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:12.10.0"
    depends_on:
      - frontend
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_BASE_URL=http://frontend:3000
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e