version: "3"

services:
  django:
    build:
      context: .
      dockerfile: ./docker/backend/unittests/django/Dockerfile
    image: secobserve_backend_unittests
    environment:
      # --- Django ---
      DJANGO_DEBUG: "True"
      # --- Admin user ---
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@example.com
      # --- Database ---
      DATABASE_ENGINE: django.db.backends.sqlite3
      # --- Security ---
      ALLOWED_HOSTS: localhost
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      DJANGO_SECRET_KEY: NxYPEF5lNGgk3yonndjSbwP77uNJxOvfKTjF5aVBqsHktNlf1wfJHHvJ8iifk32r
      FIELD_ENCRYPTION_KEY: DtlkqVb3wlaVdJK_BU-3mB4wwuuf8xx8YNInajiJ7GU=
      # --- OpenID Connect ---
      OIDC_AUTHORITY: https://authority
      OIDC_CLIENT_ID: client_id
      OIDC_USERNAME: preferred_username
      OIDC_FIRST_NAME: given_name
      OIDC_LAST_NAME: family_name
      OIDC_FULL_NAME: name
      OIDC_EMAIL: email
      OIDC_GROUPS: groups
    command: /start
