{{- if or .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "secobserve.fullname" . }}-ing
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "secobserve.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ include "secobserve.fullname" . }}-svc
                port:
                  name: backend-http
          - path: /django-static/
            pathType: Prefix
            backend:
              service:
                name: {{ include "secobserve.fullname" . }}-svc
                port:
                  name: backend-http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "secobserve.fullname" . }}-svc
                port:
                  name: frontend-http
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- if .Values.ingress.paths }}
{{- tpl (toYaml .Values.ingress.paths | indent 8) . }}
{{- end }}
{{- end }}
