# Generated by Django 3.2.16 on 2022-12-03 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0002_rules_enhancement"),
        ("core", "0002_product_ms_teams_webhook"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observation",
            old_name="status",
            new_name="current_status",
        ),
        migrations.AddField(
            model_name="observation",
            name="assessment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Resolved", "Resolved"),
                    ("Duplicate", "Duplicate"),
                    ("False positive", "False positive"),
                    ("In review", "In review"),
                    ("Not affected", "Not affected"),
                    ("Risk accepted", "Risk accepted"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="general_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="general_rules",
                to="rules.rule",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="parser_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Resolved", "Resolved"),
                    ("Duplicate", "Duplicate"),
                    ("False positive", "False positive"),
                    ("In review", "In review"),
                    ("Not affected", "Not affected"),
                    ("Risk accepted", "Risk accepted"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="product_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_rules",
                to="rules.rule",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unkown", "Unkown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Resolved", "Resolved"),
                    ("Duplicate", "Duplicate"),
                    ("False positive", "False positive"),
                    ("In review", "In review"),
                    ("Not affected", "Not affected"),
                    ("Risk accepted", "Risk accepted"),
                ],
                max_length=16,
            ),
        ),
    ]
