# Generated by Django 3.2.16 on 2022-12-15 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rules_enhancement"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="last_observation_log",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
