# Generated by Django 3.2.17 on 2023-02-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_manual_parser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parser",
            name="type",
            field=models.CharField(
                choices=[
                    ("SCA", "SCA"),
                    ("SAST", "SAST"),
                    ("DAST", "DAST"),
                    ("IAST", "IAST"),
                    ("Secrets", "Secrets"),
                    ("Infrastructure", "Infrastructure"),
                    ("Other", "Other"),
                    ("Manual", "Manual"),
                ],
                max_length=16,
            ),
        ),
    ]
