# Generated by Django 3.2.18 on 2023-02-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_status_not_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="origin_docker_image_name_tag_short",
            field=models.CharField(blank=True, max_length=513),
        ),
    ]
