# Generated by Django 3.2.18 on 2023-04-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_observation_initialize_short_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="issue_tracker_issue_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="issue_tracker_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="issue_tracker_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="issue_tracker_base_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="issue_tracker_epic_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="issue_tracker_labels",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="issue_tracker_project_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="issue_tracker_type",
            field=models.CharField(
                blank=True,
                choices=[("GitHub", "GitHub"), ("GitLab", "GitLab")],
                max_length=12,
            ),
        ),
    ]
