# Generated by Django 4.2 on 2023-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_issue_tracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="email_to",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
