# Generated by Django 4.2.1 on 2023-05-23 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_product_email_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="email_to",
            new_name="notification_email_to",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="ms_teams_webhook",
            new_name="notification_ms_teams_webhook",
        ),
    ]
