# Generated by Django 4.2.1 on 2023-06-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_rename_email_to_product_notification_email_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.product"),
                ),
            ],
            options={
                "unique_together": {("product", "name")},
            },
        ),
        migrations.AddField(
            model_name="observation",
            name="branch",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.branch"),
        ),
        migrations.AddField(
            model_name="product",
            name="repository_default_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repository_default_branch",
                to="core.branch",
            ),
        ),
    ]
