# Generated by Django 4.2.3 on 2023-07-12 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_branch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_observation_change",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
