# Generated by Django 4.2.3 on 2023-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_observation_epss_percentile_observation_epss_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observation_log",
            options={"ordering": ["observation", "-created"]},
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["name"], name="core_branch_name_5a8f35_idx"),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(fields=["name"], name="core_eviden_name_a6212e_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["product", "branch"], name="core_observ_product_2b0c8c_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["title"], name="core_observ_title_775f2c_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["current_severity"], name="core_observ_current_ac86ae_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["numerical_severity"], name="core_observ_numeric_0b8309_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["current_status"], name="core_observ_current_ad6d8c_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["vulnerability_id"], name="core_observ_vulnera_e3405d_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["origin_component_name_version"],
                name="core_observ_origin__87a215_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["origin_docker_image_name_tag_short"],
                name="core_observ_origin__0b591f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["origin_service_name"], name="core_observ_origin__43587c_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["origin_endpoint_hostname"],
                name="core_observ_origin__d64e0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["origin_source_file"], name="core_observ_origin__e87800_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["last_observation_log"], name="core_observ_last_ob_49e4ca_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["epss_score"], name="core_observ_epss_sc_6b5f31_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["scanner"], name="core_observ_scanner_d77e31_idx"),
        ),
        migrations.AddIndex(
            model_name="observation_log",
            index=models.Index(
                fields=["observation", "-created"],
                name="core_observ_observa_83425d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="observation_log",
            index=models.Index(fields=["-created"], name="core_observ_created_8b59b9_idx"),
        ),
        migrations.AddIndex(
            model_name="parser",
            index=models.Index(fields=["name"], name="core_parser_name_d48b0a_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="core_produc_name_be3252_idx"),
        ),
    ]
