# Generated by Django 4.2.3 on 2023-07-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_indices"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_product_group",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="product_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.product",
            ),
        ),
    ]
