# Generated by Django 4.2.7 on 2023-11-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_initialize_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="origin_component_dependencies",
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
