# Generated by Django 4.2.8 on 2023-12-27 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_observation_origin_component_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="has_potential_duplicates",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Potential_Duplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Component", "Component"), ("Source", "Source")],
                        max_length=12,
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="potential_duplicates",
                        to="core.observation",
                    ),
                ),
                (
                    "potential_duplicate_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.observation",
                    ),
                ),
            ],
            options={
                "unique_together": {("observation", "potential_duplicate_observation")},
            },
        ),
    ]
