# Generated by Django 4.2.8 on 2023-12-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_observation_has_potential_duplicates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="origin_cloud_account_subscription_project",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="observation",
            name="origin_cloud_provider",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="observation",
            name="origin_cloud_qualified_resource",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="observation",
            name="origin_cloud_resource",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="observation",
            name="origin_cloud_resource_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["origin_cloud_qualified_resource"],
                name="core_observ_origin__90d733_idx",
            ),
        ),
    ]
