# Generated by Django 4.2.9 on 2024-02-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_observation_origin_docker_image_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="issue_tracker_issue_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="issue_tracker_minimum_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unkown", "Unkown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
    ]
