# Generated by Django 4.2.10 on 2024-02-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_observation_assessment_vex_justification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cpe23",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="purl",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
