# Generated by Django 4.2.10 on 2024-03-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_product_cpe23_product_purl"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="cpe23",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branch",
            name="purl",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
