# Generated by Django 4.2.11 on 2024-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_branch_cpe23_branch_purl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="origin_component_dependencies",
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
