# Generated by Django 4.2.11 on 2024-03-24 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0035_alter_observation_origin_component_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation_log",
            name="approval_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="observation_log",
            name="approval_remark",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="observation_log",
            name="approval_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observation_logs_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="observation_log",
            name="assessment_status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Needs approval", "Needs approval"),
                    ("Rejected", "Rejected"),
                    ("Auto approved", "Auto approved"),
                    ("Removed", "Removed"),
                ],
                default="Auto approved",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="assessments_need_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="new_observations_in_review",
            field=models.BooleanField(default=False),
        ),
    ]
