# Generated by Django 4.2.11 on 2024-04-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_product_authorization_group_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation_log",
            name="comment",
            field=models.TextField(max_length=4096),
        ),
    ]
