# Generated by Django 4.2.11 on 2024-04-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_observation_log_general_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_rules_need_approval",
            field=models.BooleanField(default=False),
        ),
    ]
