# Generated by Django 5.0.4 on 2024-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_product_product_rules_need_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="parser",
            name="class_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="parser",
            name="module_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
