# Generated by Django 5.0.6 on 2024-07-02 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_observation_vex_statement_observation_vex_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="risk_acceptance_expiry_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="observation_log",
            name="risk_acceptance_expiry_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="risk_acceptance_expiry_active",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="risk_acceptance_expiry_days",
            field=models.IntegerField(
                help_text="Days before risk acceptance expires, 0 means no expiry",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
    ]
