# Generated by Django 5.0.7 on 2024-08-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_populate_observation_purl_type"),
        ("import_observations", "0006_parser_alter_api_configuration_parser"),
        ("rules", "0012_alter_rule_parser"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="observation",
                    name="parser",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="import_observations.parser",
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Parser",
                ),
            ],
            database_operations=[],
        ),
    ]
