# Generated by Django 5.0.9 on 2024-09-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_observation_origin_kubernetes_cluster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="origin_component_dependencies",
            field=models.TextField(blank=True, max_length=32768),
        ),
    ]
