# Generated by Django 5.1.2 on 2024-10-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_convert_origin_component_dependencies"),
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="license_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product",
                to="licenses.license_policy",
            ),
        ),
    ]
