# Generated by Django 5.1.2 on 2024-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_product_license_policy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="security_gate_threshold_unkown",
            new_name="security_gate_threshold_unknown",
        ),
        migrations.AlterField(
            model_name="observation",
            name="assessment_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="current_severity",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="parser_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="rule_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="observation_log",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="issue_tracker_minimum_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unknown", "Unknown"),
                    ("None", "None"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                max_length=12,
            ),
        ),
    ]
