# Generated by Django 5.1.4 on 2024-12-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_correct_risk_acceptance_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="cvss4_score",
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="cvss4_vector",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
