# Generated by Django 5.1.5 on 2025-01-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_observation_vulnerability_id_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="osv_linux_ecosystem",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AlmaLinux", "AlmaLinux"),
                    ("Alpine", "Alpine"),
                    ("Debian", "Debian"),
                    ("Mageia", "Mageia"),
                    ("openSUSE", "openSUSE"),
                    ("Photon OS", "Photon OS"),
                    ("Red Hat", "Red Hat"),
                    ("Rocky Linux", "Rocky Linux"),
                    ("SUSE", "SUSE"),
                    ("Ubuntu", "Ubuntu"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="osv_linux_release",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="osv_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="osv_linux_ecosystem",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AlmaLinux", "AlmaLinux"),
                    ("Alpine", "Alpine"),
                    ("Debian", "Debian"),
                    ("Mageia", "Mageia"),
                    ("openSUSE", "openSUSE"),
                    ("Photon OS", "Photon OS"),
                    ("Red Hat", "Red Hat"),
                    ("Rocky Linux", "Rocky Linux"),
                    ("SUSE", "SUSE"),
                    ("Ubuntu", "Ubuntu"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="osv_linux_release",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
