# Generated by Django 5.1.5 on 2025-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_branch_osv_linux_distribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="automatic_osv_scanning_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
