# Generated by Django 5.1.6 on 2025-03-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_product_automatic_osv_scanning_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="cve_found_in",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="observation",
            name="enriched_cvss_score",
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="enriched_cvss_vector",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
