# Generated by Django 5.1.7 on 2025-03-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_observation_cve_found_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="osv_linux_distribution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AlmaLinux", "AlmaLinux"),
                    ("Alpine", "Alpine"),
                    ("Chainguard", "Chainguard"),
                    ("Debian", "Debian"),
                    ("Mageia", "Mageia"),
                    ("openSUSE", "openSUSE"),
                    ("Photon OS", "Photon OS"),
                    ("Red Hat", "Red Hat"),
                    ("Rocky Linux", "Rocky Linux"),
                    ("SUSE", "SUSE"),
                    ("Ubuntu", "Ubuntu"),
                    ("Wolfi", "Wolfi"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="osv_linux_distribution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AlmaLinux", "AlmaLinux"),
                    ("Alpine", "Alpine"),
                    ("Chainguard", "Chainguard"),
                    ("Debian", "Debian"),
                    ("Mageia", "Mageia"),
                    ("openSUSE", "openSUSE"),
                    ("Photon OS", "Photon OS"),
                    ("Red Hat", "Red Hat"),
                    ("Rocky Linux", "Rocky Linux"),
                    ("SUSE", "SUSE"),
                    ("Ubuntu", "Ubuntu"),
                    ("Wolfi", "Wolfi"),
                ],
                max_length=12,
            ),
        ),
    ]
