# Generated by Django 5.2.1 on 2025-05-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_alter_branch_osv_linux_distribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="origin_source_file_link",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
