# Generated by Django 5.2.5 on 2025-08-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_product_description_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="origin_component_cyclonedx_bom_link",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
