# Generated by Django 5.2.6 on 2025-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_components_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                ("id", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("component_name", models.CharField(max_length=255)),
                ("component_version", models.CharField(blank=True, max_length=255)),
                ("component_name_version", models.CharField(blank=True, max_length=513)),
                ("component_purl", models.CharField(blank=True, max_length=255)),
                ("component_purl_type", models.CharField(blank=True, max_length=16)),
                ("component_cpe", models.CharField(blank=True, max_length=255)),
                ("component_dependencies", models.TextField(blank=True, max_length=32768)),
                ("component_cyclonedx_bom_link", models.CharField(blank=True, max_length=512)),
                ("has_observations", models.BooleanField()),
            ],
            options={
                "db_table": "core_component",
                "managed": False,
            },
        ),
    ]
