# Generated by Django 4.2.10 on 2024-03-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_product_cpe23_product_purl"),
        ("vex", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenVEX_Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openvexes",
                        to="core.branch",
                    ),
                ),
                (
                    "openvex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="vex.openvex",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CSAF_Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csafs",
                        to="core.branch",
                    ),
                ),
                (
                    "csaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="vex.csaf",
                    ),
                ),
            ],
        ),
    ]
