# Generated by Django 4.2.11 on 2024-03-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vex", "0003_alter_csaf_document_base_id_alter_csaf_document_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openvex",
            name="id_namespace",
            field=models.CharField(default="https://openvex.dev", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="csaf",
            name="document_id_prefix",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="openvex",
            name="document_id_prefix",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="vex_counter",
            name="document_id_prefix",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="csaf",
            unique_together={("document_id_prefix", "document_base_id")},
        ),
        migrations.AlterUniqueTogether(
            name="openvex",
            unique_together={("document_id_prefix", "document_base_id")},
        ),
        migrations.RemoveField(
            model_name="csaf",
            name="document_id",
        ),
        migrations.RemoveField(
            model_name="openvex",
            name="document_id",
        ),
    ]
