# Generated by Django 4.2.11 on 2024-03-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vex", "0004_openvex_id_namespace_alter_csaf_document_id_prefix_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vex_counter",
            options={
                "verbose_name": "VEX Counter",
                "verbose_name_plural": "VEX Counters",
            },
        ),
    ]
