# Generated by Django 5.0.8 on 2024-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vex", "0006_vex_document_vex_statement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csaf",
            name="tracking_current_release_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="csaf",
            name="tracking_initial_release_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="openvex",
            name="last_updated",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="openvex",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
