# Generated by Django 5.2.4 on 2025-07-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vex", "0007_alter_csaf_tracking_current_release_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vex_document",
            name="type",
            field=models.CharField(
                choices=[("CSAF", "CSAF"), ("OpenVEX", "OpenVEX"), ("CycloneDX", "CycloneDX")], max_length=16
            ),
        ),
    ]
