# Generated by Django 5.2.5 on 2025-08-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vex", "0008_alter_vex_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vex_statement",
            name="component_cyclonedx_bom_link",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
