# Generated by Django 5.1.2 on 2024-10-17 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "import_observations",
            "0007_api_configuration_automatic_import_branch_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spdx_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("reference", models.TextField(blank=True, max_length=2048)),
                ("is_osi_approved", models.BooleanField(null=True)),
                ("is_deprecated", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="License_Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, max_length=2048)),
                ("is_public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=255)),
                ("name_version", models.CharField(blank=True, max_length=513)),
                ("purl", models.CharField(blank=True, max_length=255)),
                ("purl_type", models.CharField(blank=True, max_length=16)),
                ("cpe", models.CharField(blank=True, max_length=255)),
                ("dependencies", models.TextField(blank=True, max_length=32768)),
                ("unknown_license", models.CharField(blank=True, max_length=255)),
                (
                    "license_policy_evalution_result",
                    models.CharField(
                        choices=[
                            ("Allowed", "Allowed"),
                            ("Forbidden", "Forbidden"),
                            ("Unkown", "Unkown"),
                        ],
                        default="Unkown",
                        max_length=16,
                    ),
                ),
                (
                    "vulnerability_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="import_observations.vulnerability_check",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licenses.license",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License_Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, max_length=2048)),
                (
                    "licenses",
                    models.ManyToManyField(
                        related_name="license_groups", to="licenses.license"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License_Policy_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unknown_license", models.CharField(blank=True, max_length=255)),
                (
                    "evaluation_result",
                    models.CharField(
                        choices=[
                            ("Allowed", "Allowed"),
                            ("Forbidden", "Forbidden"),
                            ("Unkown", "Unkown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="licenses.license",
                    ),
                ),
                (
                    "license_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licenses.license_group",
                    ),
                ),
                (
                    "license_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_policy_items",
                        to="licenses.license_policy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License_Policy_Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_manager", models.BooleanField(default=False)),
                (
                    "license_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licenses.license_policy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("license_policy", "user")},
            },
        ),
        migrations.AddField(
            model_name="license_policy",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="license_policies",
                through="licenses.License_Policy_Member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
