# Generated by Django 5.1.2 on 2024-10-25 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="license_policy",
            name="ignore_component_types",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="license_component",
            name="evaluation_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Allowed", "Allowed"),
                    ("Forbidden", "Forbidden"),
                    ("Ignored", "Ignored"),
                    ("Review required", "Review required"),
                    ("Unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="license_component",
            name="numerical_evaluation_result",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="license_policy_item",
            name="evaluation_result",
            field=models.CharField(
                choices=[
                    ("Allowed", "Allowed"),
                    ("Forbidden", "Forbidden"),
                    ("Ignored", "Ignored"),
                    ("Review required", "Review required"),
                    ("Unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="license_policy_item",
            name="numerical_evaluation_result",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
