# Generated by Django 5.1.2 on 2024-10-27 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_convert_unknown_data"),
        ("licenses", "0003_license_policy_ignore_component_types_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="license_component",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_components",
                to="core.branch",
            ),
        ),
        migrations.AlterField(
            model_name="license_component",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_components",
                to="licenses.license",
            ),
        ),
        migrations.AlterField(
            model_name="license_component",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="license_components",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="license_group_member",
            name="license_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_group_members",
                to="licenses.license_group",
            ),
        ),
        migrations.AlterField(
            model_name="license_group_member",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_group_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="license_policy_item",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="license_policy_items",
                to="licenses.license",
            ),
        ),
        migrations.AlterField(
            model_name="license_policy_item",
            name="license_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_policy_items",
                to="licenses.license_group",
            ),
        ),
        migrations.AlterField(
            model_name="license_policy_member",
            name="license_policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_policy_members",
                to="licenses.license_policy",
            ),
        ),
        migrations.AlterField(
            model_name="license_policy_member",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_policy_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
