# Generated by Django 5.1.2 on 2024-10-29 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0004_alter_license_component_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="license_component",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="license_component",
            name="import_last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="license_component",
            name="last_change",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
