# Generated by Django 5.1.2 on 2024-11-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0010_authorization_group_member_and_more"),
        ("licenses", "0005_license_component_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="License_Group_Authorization_Group_Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_manager", models.BooleanField(default=False)),
                (
                    "authorization_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_group_authorization_group_members",
                        to="access_control.authorization_group",
                    ),
                ),
                (
                    "license_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_group_authorization_group_members",
                        to="licenses.license_group",
                    ),
                ),
            ],
            options={
                "unique_together": {("license_group", "authorization_group")},
            },
        ),
        migrations.AddField(
            model_name="license_group",
            name="authorization_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="license_groups",
                through="licenses.License_Group_Authorization_Group_Member",
                to="access_control.authorization_group",
            ),
        ),
        migrations.CreateModel(
            name="License_Policy_Authorization_Group_Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_manager", models.BooleanField(default=False)),
                (
                    "authorization_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_policy_authorization_group_members",
                        to="access_control.authorization_group",
                    ),
                ),
                (
                    "license_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_policy_authorization_group_members",
                        to="licenses.license_policy",
                    ),
                ),
            ],
            options={
                "unique_together": {("license_policy", "authorization_group")},
            },
        ),
        migrations.AddField(
            model_name="license_policy",
            name="authorization_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="license_policies",
                through="licenses.License_Policy_Authorization_Group_Member",
                to="access_control.authorization_group",
            ),
        ),
    ]
