# Generated by Django 5.1.3 on 2024-11-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0006_license_group_authorization_group_member_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="License_Component_Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("evidence", models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["name"], name="licenses_li_name_32bac3_idx"),
        ),
        migrations.AddField(
            model_name="license_component_evidence",
            name="license_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidences",
                to="licenses.license_component",
            ),
        ),
        migrations.AddIndex(
            model_name="license_component_evidence",
            index=models.Index(fields=["name"], name="licenses_li_name_1eb60b_idx"),
        ),
    ]
