# Generated by Django 5.1.3 on 2024-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0009_license_component_license_expression_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="license_component",
            name="license_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
