# Generated by Django 5.1.4 on 2024-12-19 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0012_update_license_names_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="license_policy",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="licenses.license_policy",
            ),
        ),
        migrations.AddField(
            model_name="license_policy_item",
            name="comment",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
