# Generated by Django 5.1.4 on 2025-01-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0013_license_policy_parent_license_policy_item_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="license_component",
            old_name="unknown_license",
            new_name="non_spdx_license",
        ),
        migrations.RenameField(
            model_name="license_policy_item",
            old_name="unknown_license",
            new_name="non_spdx_license",
        ),
    ]
