# Generated by Django 5.1.4 on 2025-01-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "licenses",
            "0014_rename_unknown_license_license_component_non_spdx_license_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="license_component",
            old_name="cpe",
            new_name="component_cpe",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="dependencies",
            new_name="component_dependencies",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="name",
            new_name="component_name",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="name_version",
            new_name="component_name_version",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="purl",
            new_name="component_purl",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="purl_type",
            new_name="component_purl_type",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="version",
            new_name="component_version",
        ),
    ]
