# Generated by Django 5.1.7 on 2025-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0015_rename_cpe_license_component_component_cpe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="license_component",
            name="multiple_licenses",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
