# Generated by Django 5.1.5 on 2025-01-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0015_rename_cpe_license_component_component_cpe_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="license_policy",
            old_name="ignore_component_types",
            new_name="ignore_purl_types",
        ),
    ]
