# Generated by Django 5.2.1 on 2025-05-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_alter_branch_osv_linux_distribution_and_more"),
        ("licenses", "0016_license_component_multiple_licenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="license_component",
            name="origin_service",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.service"),
        ),
    ]
