# Generated by Django 5.2.5 on 2025-08-07 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_product_description_markdown"),
        ("licenses", "0017_license_component_origin_service"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="license_component",
            old_name="license",
            new_name="imported_declared_spdx_license",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="license_expression",
            new_name="imported_declared_license_expression",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="license_name",
            new_name="imported_declared_license_name",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="multiple_licenses",
            new_name="imported_declared_multiple_licenses",
        ),
        migrations.RenameField(
            model_name="license_component",
            old_name="non_spdx_license",
            new_name="imported_declared_non_spdx_license",
        ),
        migrations.AlterField(
            model_name="license_component",
            name="imported_declared_license_name",
            field=models.CharField(blank=True, default="No license information", max_length=255),
        ),
        migrations.AlterField(
            model_name="license_component",
            name="imported_declared_spdx_license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imported_declared_license_components",
                to="licenses.license",
            ),
        ),
        migrations.AddField(
            model_name="license_component",
            name="imported_concluded_spdx_license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imported_concluded_license_components",
                to="licenses.license",
            ),
        ),
        migrations.AddField(
            model_name="license_component",
            name="imported_concluded_license_expression",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="license_component",
            name="imported_concluded_license_name",
            field=models.CharField(blank=True, default="No license information", max_length=255),
        ),
        migrations.AddField(
            model_name="license_component",
            name="imported_concluded_multiple_licenses",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="license_component",
            name="imported_concluded_non_spdx_license",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="license_component",
            name="concluded_spdx_license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="concluded_license_components",
                to="licenses.license",
            ),
        ),
        migrations.AddField(
            model_name="license_component",
            name="concluded_license_expression",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="license_component",
            name="concluded_license_name",
            field=models.CharField(blank=True, default="No license information", max_length=255),
        ),
        migrations.AddField(
            model_name="license_component",
            name="concluded_non_spdx_license",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="license_component",
            name="effective_spdx_license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="effective_license_components",
                to="licenses.license",
            ),
        ),
        migrations.AddField(
            model_name="license_component",
            name="effective_license_expression",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="license_component",
            name="effective_license_name",
            field=models.CharField(blank=True, default="No license information", max_length=255),
        ),
        migrations.AddField(
            model_name="license_component",
            name="effective_multiple_licenses",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="license_component",
            name="effective_non_spdx_license",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="license_component",
            name="concluded_comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="Concluded_License",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("component_purl_type", models.CharField(blank=True, max_length=16)),
                ("component_name", models.CharField(max_length=255)),
                ("component_version", models.CharField(blank=True, max_length=255)),
                ("concluded_license_expression", models.CharField(blank=True, max_length=255)),
                ("concluded_non_spdx_license", models.CharField(blank=True, max_length=255)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "concluded_spdx_license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concluded_licenses",
                        to="licenses.license",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concluded_licenses",
                        to="core.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concluded_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "component_purl_type", "component_name", "component_version")},
            },
        ),
    ]
