# Generated by Django 5.2.5 on 2025-08-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0019_initialize_effective_licenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="license_component",
            name="component_cyclonedx_bom_link",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
