export const ROLE_CHOICES = [
    { id: 1, name: "Reader" },
    { id: 2, name: "Upload" },
    { id: 3, name: "Writer" },
    { id: 4, name: "Maintainer" },
    { id: 5, name: "Owner" },
];

export const PERMISSION_PRODUCT_GROUP_VIEW = 1001;
export const PERMISSION_PRODUCT_GROUP_EDIT = 1002;
export const PERMISSION_PRODUCT_GROUP_DELETE = 1003;
export const PERMISSION_PRODUCT_GROUP_CREATE = 1004;

export const PERMISSION_PRODUCT_VIEW = 1101;
export const PERMISSION_PRODUCT_EDIT = 1102;
export const PERMISSION_PRODUCT_DELETE = 1103;
export const PERMISSION_PRODUCT_CREATE = 1104;
export const PERMISSION_PRODUCT_IMPORT_OBSERVATIONS = 1105;

export const PERMISSION_PRODUCT_MEMBER_VIEW = 1201;
export const PERMISSION_PRODUCT_MEMBER_EDIT = 1202;
export const PERMISSION_PRODUCT_MEMBER_DELETE = 1203;
export const PERMISSION_PRODUCT_MEMBER_CREATE = 1204;

export const PERMISSION_PRODUCT_AUTHORIZATION_GROUP_MEMBER_VIEW = 1601;
export const PERMISSION_PRODUCT_AUTHORIZATION_GROUP_MEMBER_EDIT = 1602;
export const PERMISSION_PRODUCT_AUTHORIZATION_GROUP_MEMBER_DELETE = 1603;
export const PERMISSION_PRODUCT_AUTHORIZATION_GROUP_MEMBER_CREATE = 1604;

export const PERMISSION_PRODUCT_RULE_VIEW = 1301;
export const PERMISSION_PRODUCT_RULE_EDIT = 1302;
export const PERMISSION_PRODUCT_RULE_DELETE = 1303;
export const PERMISSION_PRODUCT_RULE_CREATE = 1304;
export const PERMISSION_PRODUCT_RULE_APPLY = 1305;
export const PERMISSION_PRODUCT_RULE_APPROVAL = 1306;

export const PERMISSION_BRANCH_VIEW = 1401;
export const PERMISSION_BRANCH_EDIT = 1402;
export const PERMISSION_BRANCH_DELETE = 1403;
export const PERMISSION_BRANCH_CREATE = 1404;

export const PERMISSION_SERVICE_VIEW = 1501;
export const PERMISSION_SERVICE_DELETE = 1503;

export const PERMISSION_OBSERVATION_VIEW = 2001;
export const PERMISSION_OBSERVATION_EDIT = 2002;
export const PERMISSION_OBSERVATION_DELETE = 2003;
export const PERMISSION_OBSERVATION_CREATE = 2004;
export const PERMISSION_OBSERVATION_ASSESSMENT = 2005;

export const PERMISSION_OBSERVATION_LOG_APPROVAL = 2101;

export const PERMISSION_API_CONFIGURATION_VIEW = 3001;
export const PERMISSION_API_CONFIGURATION_EDIT = 3002;
export const PERMISSION_API_CONFIGURATION_DELETE = 3003;
export const PERMISSION_API_CONFIGURATION_CREATE = 3004;

export const PERMISSION_PRODUCT_API_TOKEN_REVOKE = 4003;
export const PERMISSION_PRODUCT_API_TOKEN_CREATE = 4004;

export const PERMISSION_VEX_VIEW = 5001;
export const PERMISSION_VEX_EDIT = 5002;
export const PERMISSION_VEX_DELETE = 5003;
export const PERMISSION_VEX_CREATE = 5004;

export const PERMISSION_COMPONENT_LICENSE_EDIT = 6002;
export const PERMISSION_COMPONENT_LICENSE_DELETE = 6003;

export const PERMISSION_CONCLUDED_LICENSE_VIEW = 7001;
export const PERMISSION_CONCLUDED_LICENSE_EDIT = 7002;
export const PERMISSION_CONCLUDED_LICENSE_DELETE = 7003;
export const PERMISSION_CONCLUDED_LICENSE_CREATE = 7004;
