# Generated by Django 5.2.4 on 2025-07-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Periodic_Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("duration", models.BigIntegerField(help_text="Duration in milliseconds", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Running", "Running"), ("Success", "Success"), ("Failure", "Failure")], max_length=10
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["task", "-start_time"], name="background__task_6102f3_idx"),
                    models.Index(fields=["-start_time"], name="background__start_t_224633_idx"),
                    models.Index(fields=["status"], name="background__status_2d3bb2_idx"),
                    models.Index(fields=["duration"], name="background__duratio_c2bf22_idx"),
                ],
            },
        ),
    ]
