# Generated by Django 3.2.16 on 2022-12-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_rules_enhancement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rule",
            old_name="new_parser_severity",
            new_name="new_severity",
        ),
    ]
