# Generated by Django 3.2.16 on 2022-12-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0003_rename_new_parser_severity_rule_new_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
