# Generated by Django 3.2.16 on 2022-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rules_enhancement"),
        ("rules", "0004_rule_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="rule",
            unique_together={("product", "name")},
        ),
    ]
