# Generated by Django 4.2.3 on 2023-07-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0006_status_not_security"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(fields=["name"], name="rules_rule_name_d986dc_idx"),
        ),
    ]
