# Generated by Django 4.2.8 on 2023-12-17 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_observation_origin_component_dependencies"),
        ("rules", "0007_indices"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="description_observation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rule",
            name="parser",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.parser"),
        ),
    ]
