# Generated by Django 4.2.8 on 2023-12-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0008_rule_description_observation_alter_rule_parser"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="origin_cloud_qualified_resource",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
