# Generated by Django 4.2.11 on 2024-04-30 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rules", "0010_rule_new_vex_justification"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="approval_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="approval_remark",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="rule",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Needs approval", "Needs approval"),
                    ("Rejected", "Rejected"),
                    ("Auto approved", "Auto approved"),
                ],
                default="Auto approved",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rule",
            name="approval_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rule_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rule",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
