# Generated by Django 5.0.7 on 2024-08-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_observations", "0006_parser_alter_api_configuration_parser"),
        ("rules", "0011_rule_approval_date_rule_approval_remark_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="rule",
                    name="parser",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="import_observations.parser",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
