# Generated by Django 5.2.5 on 2025-08-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0015_convert_unknown_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="new_vex_justification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("component_not_present", "component_not_present"),
                    ("vulnerable_code_not_present", "vulnerable_code_not_present"),
                    (
                        "vulnerable_code_cannot_be_controlled_by_adversary",
                        "vulnerable_code_cannot_be_controlled_by_adversary",
                    ),
                    ("vulnerable_code_not_in_execute_path", "vulnerable_code_not_in_execute_path"),
                    ("inline_mitigations_already_exist", "inline_mitigations_already_exist"),
                    ("code_not_present", "code_not_present"),
                    ("code_not_reachable", "code_not_reachable"),
                    ("requires_configuration", "requires_configuration"),
                    ("requires_dependency", "requires_dependency"),
                    ("requires_environment", "requires_environment"),
                    ("protected_by_compiler", "protected_by_compiler"),
                    ("protected_at_runtime", "protected_at_runtime"),
                    ("protected_at_perimeter", "protected_at_perimeter"),
                    ("protected_by_mitigating_control", "protected_by_mitigating_control"),
                ],
                max_length=64,
            ),
        ),
    ]
