# Generated by Django 5.1.8 on 2025-04-15 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0062_alter_branch_osv_linux_distribution_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Notification",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("created", models.DateTimeField(auto_now_add=True)),
                        ("message", models.TextField(max_length=4096)),
                        (
                            "type",
                            models.CharField(
                                choices=[
                                    ("Exception", "Exception"),
                                    ("Security gate", "Security gate"),
                                    ("Task", "Task"),
                                ],
                                max_length=20,
                            ),
                        ),
                        ("function", models.CharField(blank=True, max_length=255)),
                        ("arguments", models.TextField(blank=True, max_length=4096)),
                        (
                            "observation",
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.observation"
                            ),
                        ),
                        (
                            "product",
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.product"
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                            ),
                        ),
                    ],
                    options={
                        "db_table": "commons_notification",
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Notification_Viewed",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        (
                            "notification",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="notifications.notification"
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                        ),
                    ],
                    options={
                        "db_table": "commons_notification_viewed",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
