class Rule_Status:
    RULE_STATUS_APPROVED = "Approved"
    RULE_STATUS_NEEDS_APPROVAL = "Needs approval"
    RULE_STATUS_REJECTED = "Rejected"
    RULE_STATUS_AUTO_APPROVED = "Auto approved"

    RULE_STATUS_CHOICES = [
        (RULE_STATUS_APPROVED, RULE_STATUS_APPROVED),
        (RULE_STATUS_NEEDS_APPROVAL, RULE_STATUS_NEEDS_APPROVAL),
        (RULE_STATUS_REJECTED, RULE_STATUS_REJECTED),
        (RULE_STATUS_AUTO_APPROVED, RULE_STATUS_AUTO_APPROVED),
    ]

    RULE_STATUS_CHOICES_APPROVAL = [
        (RULE_STATUS_APPROVED, RULE_STATUS_APPROVED),
        (RULE_STATUS_REJECTED, RULE_STATUS_REJECTED),
    ]
