# Generated by Django 3.2.16 on 2022-11-17 22:49

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Api_Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.CharField(max_length=255)),
                ("project_key", models.CharField(max_length=255)),
                ("api_key", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "parser",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.parser"),
                ),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.product"),
                ),
            ],
            options={
                "unique_together": {("product", "name")},
            },
        ),
    ]
