# Generated by Django 4.2.6 on 2023-10-31 19:11

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models
from encrypted_model_fields.fields import EncryptedCharField


class Migration(migrations.Migration):
    dependencies = [
        ("import_observations", "0004_zap_rename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Api_Configuration",
            name="project_key",
            field=models.CharField(
                blank=True, null=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="Api_Configuration",
            name="api_key",
            field=EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name='Api_Configuration',
            name='query',
            field=models.CharField(
                max_length=255, blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name='Api_Configuration',
            name='basic_auth_enabled',
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name='Api_Configuration',
            name='verify_ssl',
            field=models.BooleanField()
        ),
        migrations.AddField(
            model_name='Api_Configuration',
            name='basic_auth_username',
            field=models.CharField(
                max_length=255, blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name='Api_Configuration',
            name='basic_auth_password',
            field=EncryptedCharField(
                max_length=255, blank=True, null=True
            ),
        ),       
    ]
