# Generated by Django 5.0.7 on 2024-08-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_observations", "0005_api_configuration_basic_auth_enabled_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Parser",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=255, unique=True)),
                        (
                            "type",
                            models.CharField(
                                choices=[
                                    ("SCA", "SCA"),
                                    ("SAST", "SAST"),
                                    ("DAST", "DAST"),
                                    ("IAST", "IAST"),
                                    ("Secrets", "Secrets"),
                                    ("Infrastructure", "Infrastructure"),
                                    ("Other", "Other"),
                                    ("Manual", "Manual"),
                                ],
                                max_length=16,
                            ),
                        ),
                        (
                            "source",
                            models.CharField(
                                choices=[
                                    ("API", "API"),
                                    ("File", "File"),
                                    ("Manual", "Manual"),
                                    ("Unkown", "Unkown"),
                                ],
                                max_length=16,
                            ),
                        ),
                        ("module_name", models.CharField(blank=True, max_length=255)),
                        ("class_name", models.CharField(blank=True, max_length=255)),
                    ],
                    options={
                        "db_table": "core_parser",
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="parser",
                    index=models.Index(fields=["name"], name="core_parser_name_d48b0a_idx"),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="api_configuration",
                    name="parser",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="import_observations.parser",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
