# Generated by Django 5.1.5 on 2025-01-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "import_observations",
            "0010_vulnerability_check_last_import_licenses_deleted_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OSV_Cache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osv_id", models.CharField(max_length=255, unique=True)),
                ("data", models.TextField()),
                ("modified", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="parser",
            name="source",
            field=models.CharField(
                choices=[
                    ("API", "API"),
                    ("File", "File"),
                    ("Manual", "Manual"),
                    ("Other", "Other"),
                    ("Unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
    ]
