# Generated by Django 5.2.7 on 2025-10-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("import_observations", "0013_alter_vulnerability_check_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="api_configuration",
            old_name="automatic_import_service",
            new_name="automatic_import_service_name",
        ),
    ]
