# Generated by Django 5.2.7 on 2025-10-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_components_view_open_observations"),
        ("import_observations", "0014_rename_automatic_import_service_api_configuration_automatic_import_service_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="api_configuration",
            old_name="automatic_import_service_name",
            new_name="automatic_import_service_legacy",
        ),
        migrations.AddField(
            model_name="api_configuration",
            name="automatic_import_service",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="core.service"),
        ),
    ]
