# Generated by Django 4.2.11 on 2024-04-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0004_settings_feature_disable_user_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="feature_general_rules_need_approval",
            field=models.BooleanField(default=False, help_text="General rules need approval"),
        ),
    ]
