# Generated by Django 5.0.6 on 2024-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0005_settings_feature_general_rules_need_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="internal_users",
            field=models.CharField(
                blank=True,
                help_text="Comma separated list of email regular expressions to identify internal users",
                max_length=255,
            ),
        ),
    ]
