# Generated by Django 5.0.8 on 2024-09-02 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0007_settings_risk_acceptance_expiry_crontab_hours_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings",
            old_name="background_epss_import_crontab_hours",
            new_name="background_epss_import_crontab_hour",
        ),
        migrations.RenameField(
            model_name="settings",
            old_name="background_epss_import_crontab_minutes",
            new_name="background_epss_import_crontab_minute",
        ),
        migrations.RenameField(
            model_name="settings",
            old_name="branch_housekeeping_crontab_hours",
            new_name="branch_housekeeping_crontab_hour",
        ),
        migrations.RenameField(
            model_name="settings",
            old_name="branch_housekeeping_crontab_minutes",
            new_name="branch_housekeeping_crontab_minute",
        ),
        migrations.RenameField(
            model_name="settings",
            old_name="risk_acceptance_expiry_crontab_hours",
            new_name="risk_acceptance_expiry_crontab_hour",
        ),
        migrations.RenameField(
            model_name="settings",
            old_name="risk_acceptance_expiry_crontab_minutes",
            new_name="risk_acceptance_expiry_crontab_minute",
        ),
        migrations.AddField(
            model_name="settings",
            name="feature_automatic_api_import",
            field=models.BooleanField(default=True, help_text="Enable automatic API imports"),
        ),
        migrations.AddField(
            model_name="settings",
            name="api_import_crontab_hour",
            field=models.IntegerField(
                default=4,
                help_text="Hour crontab expression for API imports (UTC)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="api_import_crontab_minute",
            field=models.IntegerField(
                default=0,
                help_text="Minute crontab expression for API imports",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="background_epss_import_crontab_hour",
            field=models.IntegerField(
                default=3,
                help_text="Hour crontab expression for EPSS import (UTC)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="background_epss_import_crontab_minute",
            field=models.IntegerField(
                default=0,
                help_text="Minute crontab expression for EPSS import",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="branch_housekeeping_crontab_hour",
            field=models.IntegerField(
                default=2,
                help_text="Hour crontab expression for branch housekeeping (UTC)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="branch_housekeeping_crontab_minute",
            field=models.IntegerField(
                default=0,
                help_text="Minute crontab expression for branch housekeeping",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="risk_acceptance_expiry_crontab_hour",
            field=models.IntegerField(
                default=1,
                help_text="Hour crontab expression for checking risk acceptance expiry (UTC)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="risk_acceptance_expiry_crontab_minute",
            field=models.IntegerField(
                default=0,
                help_text="Minute crontab expression for checking risk acceptance expiry",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(59),
                ],
            ),
        ),
    ]
