# Generated by Django 5.1.2 on 2024-10-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0010_settings_feature_license_management_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings",
            old_name="security_gate_threshold_unkown",
            new_name="security_gate_threshold_unknown",
        ),
    ]
