# Generated by Django 5.1.2 on 2024-10-24 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0011_rename_settings_security_gate_threshold_unkown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="security_gate_threshold_unknown",
            field=models.IntegerField(
                default=99999,
                help_text="Number of unknown observations that must not be exceeded",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
    ]
