# Generated by Django 5.1.5 on 2025-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0013_notification_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="feature_automatic_osv_scanning",
            field=models.BooleanField(default=True, help_text="Enable automatic OSV scanning"),
        ),
    ]
