# Generated by Django 5.1.6 on 2025-03-06 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0014_settings_feature_automatic_osv_scanning"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="cvss_enrichment_max_age_years",
            field=models.IntegerField(
                default=10,
                help_text="Maximum age of CVEs for enrichment in years",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="feature_cvss_enrichment",
            field=models.BooleanField(default=True, help_text="Enable CVSS enrichment"),
        ),
    ]
