# Generated by Django 5.2.4 on 2025-07-21 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0016_remove_notification_viewed_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="periodic_task_max_entries",
            field=models.IntegerField(
                default=10,
                help_text="Maximum number of entries to keep per periodic task",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
    ]
