# Generated by Django 5.2.5 on 2025-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0017_settings_periodic_task_max_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="vex_justification_style",
            field=models.CharField(
                choices=[("CSAF/OpenVEX", "CSAF/OpenVEX"), ("CycloneDX", "CycloneDX")],
                default="CSAF/OpenVEX",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="feature_vex",
            field=models.BooleanField(default=False, help_text="Export and import VEX documents in various formats"),
        ),
    ]
