# Generated by Django 3.2.16 on 2022-11-12 16:43

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0002_user_additional_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="API_Token",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="access_control.user",
                    ),
                ),
                ("api_token_hash", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "API token",
                "verbose_name_plural": "API token",
            },
        ),
        migrations.CreateModel(
            name="JWT_Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", encrypted_model_fields.fields.EncryptedCharField()),
            ],
            options={
                "verbose_name": "JWT secret",
            },
        ),
    ]
