# Generated by Django 3.2.16 on 2022-11-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0003_api_token_jwt_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api_token",
            name="api_token_hash",
            field=models.CharField(max_length=255),
        ),
    ]
