# Generated by Django 4.2.6 on 2023-10-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0005_user_setting_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="setting_list_properties",
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
