# Generated by Django 4.2.8 on 2024-01-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0006_user_setting_list_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="setting_list_size",
            field=models.CharField(
                choices=[("small", "small"), ("medium", "medium")],
                default="medium",
                max_length=6,
            ),
        ),
    ]
