# Generated by Django 4.2.11 on 2024-03-26 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0007_user_setting_list_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="oidc_groups_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("oidc_group", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="so_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "indexes": [
                    models.Index(
                        fields=["oidc_group"], name="access_cont_oidc_gr_992592_idx"
                    )
                ],
            },
        ),
    ]
