# Generated by Django 4.2.11 on 2024-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0008_user_oidc_groups_hash_authorization_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_oidc_user",
            field=models.BooleanField(default=False),
        ),
    ]
