# Generated by Django 5.2.8 on 2025-11-13 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0011_user_setting_package_info_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api_token",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="api_token",
            name="expiration_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="api_token",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AddField(
            model_name="api_token",
            name="name",
            field=models.CharField(default="default", max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name="api_token",
            unique_together={("user", "name")},
        ),
    ]
