# Generated by Django 5.2.8 on 2025-11-19 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0012_api_token_expiration_date_api_token_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="API_Token_Multiple",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="default", max_length=32)),
                ("api_token_hash", models.CharField(max_length=255)),
                ("expiration_date", models.DateField(null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "API token",
                "verbose_name_plural": "API token",
                "unique_together": {("user", "name")},
            },
        ),
    ]
