#!/bin/sh

set -o errexit

rm -f /var/lib/sqlite/secobserve.db
python manage.py migrate

coverage run /app/manage.py test unittests
# coverage run /app/manage.py test unittests.authorization.api.test_authorization_concluded_licenses
coverage report
coverage xml -o /home/coverage.xml
