#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

rm -f /var/lib/sqlite/secobserve.db
python manage.py migrate
python manage.py register_parsers

coverage run /app/manage.py test unittests
# coverage run /app/manage.py test unittests.import_observations.scanners.test_osv_scanner
coverage report
coverage xml
# sed -i "s|/app|/|g" /home/coverage.xml
