#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

rm -f /var/lib/sqlite/secobserve.db
python manage.py migrate
python manage.py register_parsers

coverage run --branch /app/manage.py test unittests
# coverage run --branch /app/manage.py test unittests.import_observations.parsers.secobserve.test_parser
coverage report --skip-empty --show-missing
