#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

coverage run --branch /app/manage.py test unittests.access_control.api.test_authorization_authorization_groups
coverage report --skip-empty --show-missing
