#!/bin/sh

set -o errexit
set -o nounset

if [ -z "${DATABASE_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export DATABASE_USER="${base_postgres_image_default_user}"
fi

if [ "${DATABASE_ENGINE}" != "django.db.backends.sqlite3" ]; then
    /wait-for-it.sh "${DATABASE_HOST}":"${DATABASE_PORT}"
    >&2 echo 'Database is available'
fi

python manage.py migrate

echo "Admin user: ${ADMIN_USER}"
ADMIN_EXISTS=$(echo "SELECT * from access_control_user;" | python manage.py dbshell | grep "${ADMIN_USER}" || :)
if [ ! -z "$ADMIN_EXISTS" ]
then
    echo "Initialization detected that the admin user ${ADMIN_USER} already exists in your database."
else
    if [ -z "${ADMIN_PASSWORD}" ]
    then
        export ADMIN_PASSWORD="$(cat /dev/urandom | LC_ALL=C tr -dc a-zA-Z0-9 | head -c 22)"
        echo "Admin password: ${ADMIN_PASSWORD}"
    fi

    echo "Initialization detected no admin user ${ADMIN_USER}, creating it now in your database."

cat <<EOD | python manage.py shell
import os
from application.access_control.models import User
User.objects.create_superuser(
  os.getenv('ADMIN_USER'),
  os.getenv('ADMIN_EMAIL'),
  os.getenv('ADMIN_PASSWORD'),
)
EOD
fi

python manage.py run_huey --flush-locks &

python manage.py register_parsers
python manage.py initial_license_load

python manage.py runserver_plus 0.0.0.0:8000
