#!/bin/sh

set -o errexit
# set -o pipefail
set -o nounset



# N.B. If only .env files supported variable expansion...
# --- Celery/Redis is currently unused ---
# export CELERY_BROKER_URL="${REDIS_URL}"


if [ -z "${DATABASE_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export DATABASE_USER="${base_postgres_image_default_user}"
fi

/wait-for-it.sh "${DATABASE_HOST}":"${DATABASE_PORT}"
>&2 echo 'Database is available'

exec "$@"
