export const EVALUATION_RESULT_FORBIDDEN = "Forbidden";
export const EVALUATION_RESULT_REVIEW_REQUIRED = "Review required";
export const EVALUATION_RESULT_ALLOWED = "Allowed";
export const EVALUATION_RESULT_UNKNOWN = "Unknown";
export const EVALUATION_RESULT_IGNORED = "Ignored";

export const EVALUATION_RESULT_CHOICES = [
    { id: EVALUATION_RESULT_FORBIDDEN, name: EVALUATION_RESULT_FORBIDDEN },
    { id: EVALUATION_RESULT_REVIEW_REQUIRED, name: EVALUATION_RESULT_REVIEW_REQUIRED },
    { id: EVALUATION_RESULT_ALLOWED, name: EVALUATION_RESULT_ALLOWED },
    { id: EVALUATION_RESULT_UNKNOWN, name: EVALUATION_RESULT_UNKNOWN },
    { id: EVALUATION_RESULT_IGNORED, name: EVALUATION_RESULT_IGNORED },
];
