name: Check frontend

on: [push, pull_request]

permissions: read-all

jobs:
  check_frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        npm ci

    - name: Prettier
      working-directory: ./frontend
      run: |
        npx prettier -c src

    - name: ESLint
      working-directory: ./frontend
      run: |
        npx eslint src

    - name: End-to-end tests
      working-directory: .
      run: |
        cd end_to_end_tests
        npm install
        cd ..
        docker compose -f docker-compose-playwright.yml build
        docker compose -f docker-compose-playwright.yml up --abort-on-container-exit --exit-code-from playwright
