name: Check frontend

on: [push, pull_request]

permissions: read-all

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci

      - name: Prettier
        working-directory: ./frontend
        run: |
          npx prettier -c src

      - name: ESLint
        working-directory: ./frontend
        run: |
          npx eslint src

  end_to_end_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: End-to-end tests
        working-directory: .
        run: |
          cd end_to_end_tests
          npm install
          cd ..
          docker compose -f docker-compose-playwright.yml build
          docker compose -f docker-compose-playwright.yml up --abort-on-container-exit --exit-code-from playwright

  check_code_sonarqube_frontend:
    if: github.repository == 'MaibornWolff/SecObserve'
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  
      - 
        name: Run SonarQube scan for frontend
        uses: SonarSource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        with:
          projectBaseDir: frontend
