name: Check frontend

on: [push, pull_request]

permissions: read-all

jobs:
  check_frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        npm ci

    - name: Prettier
      working-directory: ./frontend
      run: |
        npx prettier -c src

    - name: ESLint
      working-directory: ./frontend
      run: |
        npx eslint src

    - name: Check build
      working-directory: ./frontend
      run: |
        npm run build

    # - name: End-to-end tests
    #   working-directory: .
    #   run: |
    #     cd end_to_end_tests
    #     npm install
    #     cd ..
    #     docker compose -f docker-compose-playwright.yml build
    #     docker compose -f docker-compose-playwright.yml up --abort-on-container-exit --exit-code-from playwright
