name: Check frontend

on: [push, pull_request]

permissions: read-all

jobs:
  check_frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Prettier
      working-directory: ./frontend
      run: |
        npx prettier -c src

    - name: ESLint
      working-directory: ./frontend
      run: |
        npx eslint src

    # - name: End-to-end tests
    #   working-directory: .
    #   run: |
    #     cd end_to_end_tests
    #     npm install
    #     cd ..
    #     docker compose -f docker-compose-playwright.yml build
    #     docker compose -f docker-compose-playwright.yml up --abort-on-container-exit --exit-code-from playwright
