name: Check frontend

on: [push]

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Prettier
      working-directory: ./frontend
      run: |
        npx prettier -c src

    - name: ESLint
      working-directory: ./frontend
      run: |
        npx eslint src

    # - name: End-to-end tests
    #   working-directory: .
    #   run: |
    #     cd end_to_end_tests
    #     npm install
    #     cd ..
    #     docker compose -f docker-compose-playwright.yml build
    #     docker compose -f docker-compose-playwright.yml up --abort-on-container-exit --exit-code-from playwright
