name: Check frontend

on: [push, pull_request]

permissions: read-all

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci

      - name: Prettier
        working-directory: ./frontend
        run: |
          npx prettier -c src

      - name: ESLint
        working-directory: ./frontend
        run: |
          npx eslint src

  end_to_end_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: End-to-end tests
        working-directory: .
        run: |
          cd end_to_end_tests
          npm install
          cd ..
          docker compose -f docker-compose-playwright.yml build
          docker compose -f docker-compose-playwright.yml up --abort-on-container-exit --exit-code-from playwright

  check_code_sonarqube_frontend:
    if: github.repository == 'MaibornWolff/SecObserve'
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0  
      - 
        name: Run SonarQube scan for frontend
        uses: SonarSource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9 # v5.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        with:
          projectBaseDir: frontend
